# Generated by Django 3.1.1 on 2020-10-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201021_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='shop_id',
            field=models.CharField(max_length=255),
        ),
    ]
